/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.41
 * Generated at: 2019-11-17 13:47:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script>\r\n");
      out.write("function openLogin() {\t// 로그인 팝업창\r\n");
      out.write("\twindow.open('login.do', 'login', 'width=400, height=200, top=200, left=700');\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div>\r\n");
      out.write("<h3>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ msg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\r\n");
      out.write("</div>\r\n");
      out.write("<h1>index페이지입니다</h1>\r\n");
      out.write("<ul>\r\n");
      out.write("<li><a href=\"hello.do\">스프링 MVC테스트</a></li>\r\n");
      out.write("<li><a href=\"memoWrite.do\">메모작성하기</a></li>\r\n");
      out.write("<li><a href=\"memberJoin.do\">회원가입</a>\r\n");
      out.write("<li><a href=\"order.do\">편의점 발주 프로그램</a></li>\r\n");
      out.write("<li><a href=\"paramTest.do?str=spring&idx=3\">파라미터 테스트</a></li>\r\n");
      out.write("<li><a href=\"cookieView.do\">쿠키 데이터 확인하기</a></li>\r\n");
      out.write("<li><a href=\"cookieMake.do\">쿠키 데이터 저장하기</a></li>\r\n");
      out.write("<li><a href=\"sessionView.do\">세션 데이터 확인하기</a></li>\r\n");
      out.write("<li><a href=\"sessionMake.do\">세션 데이터 저장하기</a></li>\r\n");
      out.write("<li><a href=\"viewTest1.do\">명시적 View 지정 방법1</a></li>\r\n");
      out.write("<li><a href=\"viewTest2.do\">명시적 View 지정 방법2</a></li>\r\n");
      out.write("<li><a href=\"view/viewOk.do\">묵시적 View 지정 방법</a></li>\r\n");
      out.write("<li><a href=\"viewTest3.do\">또 다른 명령어 호출</a></li>\r\n");
      out.write("<li><a href=\"modelTest1.do\">모델 테스트1 (Map)</a></li>\r\n");
      out.write("<li><a href=\"modelTest2.do\">모델 테스트2 (Model)</a></li>\r\n");
      out.write("<li><a href=\"modelTest3.do\">모델 테스트3 (ModelMap)</a></li>\r\n");
      out.write("<li><a href=\"model/modelOk.do\">모델 테스트4 (Map 반환)</a></li>\r\n");
      out.write("<li><a href=\"model/modelOk.do\">모델 테스트5 (Model 반환)</a></li>\r\n");
      out.write("<li><a href=\"animeFindA.do\">애니메이션 검색</a></li>\r\n");
      out.write("<li><a href=\"fileUploadForm.do\">파일업로드</a></li>\r\n");
      out.write("<li><a href=\"fileList.do\">파일 다운로드 리스트</a></li>\r\n");
      out.write("<li><a href=\"webFolder.do\">웹폴더</a></li>\r\n");
      out.write("<li><a href=\"emp.do\">사원 관리 프로그램</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
